config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get 'chat/:id' => 'chats#show', as: 'chat'
  get "/rank" => "users#rank"

  resources :users, only: [:index, :show, :edit, :update, :destroy]do
    resource :relationships, only: [:create, :destroy]
      member do
        get :following, :followers
      end
  end
  resources :posts, only: [:new, :create, :index, :show, :edit,:update, :destroy]do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :chats, only: [:create]
  resources :notifications, only: [:index, :destroy]
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true, length: { maximum: 50 }
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @post_comment = current_user.post_comments.new(post_comment_params)
    @post_comment.post_id = @post.id
    @post_comment.save
    unless @post.user == @post_comment.user
      @post.create_notification_comment(current_user, @post.user)
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post_comment = PostComment.find_by(id: params[:id], post_id: params[:post_id]).destroy
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_post_comment.html.erb
<div class="row">
  <div class="col-md-3">
    <h5>コメント一覧</h5>
  </div>
  <div class="col-md-4 offset-5">
    <h5><%= post.post_comments.count %>件のコメント</h5>
  </div>
  <div class="comment-scroll">
    <% if post.post_comments.present? %>
    <table class="table">
      <tr class="table-secondary">
        <th>ユーザー名</th>
        <th>コメント</th>
        <th></th>
        <th></th>
      </tr>
        <% post.post_comments.each do |post_comment| %>
        <tr class="bg-light">
          <td width=150>
            <%= link_to user_path(post_comment.user) do %>
              <%= post_comment.user.name %>
            <% end %>
          </td>
          <td width=300><%= post_comment.comment %></td>
          <td width=130><%= post_comment.created_at.strftime('%Y/%m/%d') %></td>
          <td width=70>
            <% if post_comment.user == current_user %>
              <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete, remote: true, class: "text-danger" %>
            <% end %><br>
          </td>
        <% end %>
      </tr>
    </table>
    <% else %>
    <% end %>
  </div>
  <div class="comment-field my-5">
    <% if post_comment.errors.any? %>
      <% post_comment.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>

    <%= form_with(model:[post, post_comment], remote: true) do |f| %>
      <%= f.text_area :comment,placeholder: "コメント", size: "50x2" %><br>
      <%= f.submit "送信する" %>
    <% end %>
  </div>
</div>

app/views/post_comments/create.js.erb
$(".comments").html("<%= escape_javascript(render partial: 'post_comments/post_comment', locals: {post: @post, post_comment: @post_comment}) %>");
$(".comments").html("<%= j(render 'post_comments/post_comment', {post: @post, post_comment: @post_comment}) %>");
$("textarea").val('')

app/views/post_comments/destroy.js.erb
$(".comments").html("<%= escape_javascript(render partial: 'post_comments/post_comment', locals: {post: @post, post_comment: @post_comment}) %>");
$(".comments").html("<%= j(render 'post_comments/post_comment', {post: @post, post_comment: @post_comment}) %>");
$("textarea").val('')