config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get 'chat/:id' => 'chats#show', as: 'chat'
  get "/rank" => "users#rank"

  resources :users, only: [:index, :show, :edit, :update, :destroy]do
    resource :relationships, only: [:create, :destroy]
      member do
        get :following, :followers
      end
  end
  resources :posts, only: [:new, :create, :index, :show, :edit,:update, :destroy]do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :chats, only: [:create]
  resources :notifications, only: [:index, :destroy]
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  #optional: trueは、nilを許可するもの
  belongs_to :post, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true 
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications
    #未確認の通知レコードだけ取り出したあと、「未確認→確認済」になるように更新
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
  
  def destroy
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_form(notification)
    #通知の一部をリンクにして、下のcase文の中で使用
    visitor = link_to notification.visitor.name, notification.visitor, class: "visitor_name"
    your_post = link_to 'あなたの投稿', notification.post, class: "your_post"
    case notification.action
      when "favorite" then
        "#{visitor}さんが#{your_post}にいいね！しました"
      when "comment" then
        "#{visitor}さんが#{your_post}にコメント！しました"
    end
  end
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<div class="user-notice">
  <h6><%== notification_form(notification) %><span><%= "(#{time_ago_in_words(notification.created_at)}前)" %></span></h6><br>
</div>

app/views/notifications/index.html.erb
<div class="row">
  <div class="col-md-3 offset-4 mt-5">
    <h5>通知</h5>
  </div>
  <div class="col-md-4 mt-5">
    <%= link_to "通知削除", notification_path(@notifications), method: :delete, data: {confirm: "削除しますか？"}, class: "text-danger fas fa-trash" %>
  </div>
</div>
<div class="row">
  <div class="col-md-6 offset-4 mt-5 pl-4">
  <table>
    <tr>
      <th>
        <% if @notifications.exists? %>
          <p><%= render @notifications %></p>
        <% else %>
          <p>通知はありません</p>
        <% end %>
      </th>
    </tr>
  </table>
  </div>
</div>