config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get 'chat/:id' => 'chats#show', as: 'chat'
  get "/rank" => "users#rank"

  resources :users, only: [:index, :show, :edit, :update, :destroy]do
    resource :relationships, only: [:create, :destroy]
      member do
        get :following, :followers
      end
  end
  resources :posts, only: [:new, :create, :index, :show, :edit,:update, :destroy]do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :chats, only: [:create]
  resources :notifications, only: [:index, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :following_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :following_relationships, source: :followed
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :user_rooms
  has_many :chats

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :name, presence: true, length: { maximum: 10 }, uniqueness: true
  validates :age, presence: true
  validates :profile_score, presence: true
  validates :introduction, length: { maximum: 150 }

  attachment :profile_image
  enum gender: { 男性: 0, 女性: 1}
  enum address:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }

  def follow(user_id)
    following_relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following.include?(user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @q = User.ransack(params[:q])
    @user_s = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    # フォロワーの投稿表示
    @users = @user.following
    @follow_post = []
    if @users.present?
      @users.each do |user|
        post_s = Post.where(user_id: user.id).order(created_at: :desc)
        #取得したユーザーの投稿一覧を@postsに格納
        @follow_post.concat(post_s)
      end
      #@postsを新しい順に並べる
      @follow_post.sort_by!{|post| post.created_at}
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to root_path
  end

  def following
     @user = User.find(params[:id])
     @users = @user.following.all
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.all
  end

  def rank
    @user_avg = User.joins(:posts).group(:id).select("AVG(posts.score) as average_score, users.*").order("average_score asc").limit(10)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :gender, :age, :address, :introduction, :profile_score)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_aaa.html.erb
<h4>投稿履歴の<br>平均スコアランキング</h4>
<% avg = 0 %>
<% rank = 1 %>
<table class="table table-hover">
  <tr class="table-secondary">
    <th>順位</th>
    <th>ユーザー名</th>
    <th>平均スコア</th>
    <th>年齢</th>
  </tr>
  <% user_avg_age.each.with_index(1) do |user, i| %>
    <tr class="bg-light">
      <% if i == 1 %>
        <% avg = user.average_score %>
      <% end %>
      <% if user.average_score != avg %>
        <% rank = i %>
        <td>第<%= rank %>位</td>
        <td>
          <%= link_to user_path(user) do %>
            <%= user.name %>
          <% end %>
        </td>
        <td><%= user.average_score %></td>
        <% avg = user.average_score %>
        <td><%= user.age %>代</td>
      <!--同順位の表示-->
      <% else %>
        <% avg = user.average_score %>
        <td>第<%= rank %>位</td>
        <td>
          <%= link_to user_path(user) do %>
            <%= user.name %>
          <% end %>
        </td>
        <td><%= user.average_score %></td>
        <td><%= user.age %>代</td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/users/_age.html.erb
<% avg = 0 %>
<% rank = 1 %>
<table class="table table-hover">
  <tr class="table-secondary">
    <th>順位</th>
    <th>ユーザー名</th>
    <th>平均スコア</th>
    <th>年齢</th>
  </tr>
  <% user_avg_age.each.with_index(1) do |user, i| %>
    <tr class="bg-light">
      <% if i == 1 %>
        <% avg = user.average_score %>
      <% end %>
      <% if user.average_score != avg %>
        <% rank = i %>
        <td>第<%= rank %>位</td>
        <td>
          <%= link_to user_path(user) do %>
            <%= user.name %>
          <% end %>
        </td>
        <td><%= user.average_score.floor(1).to_f %></td><!--to_fで小数点以下を表示させ、floor()で小数点以下の桁数を引数で指定-->
        <% avg = user.average_score %>
        <td><%= user.age %>代</td>
      <!--同順位の表示-->
      <% else %>
        <% avg = user.average_score %>
        <td>第<%= rank %>位</td>
        <td>
          <%= link_to user_path(user) do %>
            <%= user.name %>
          <% end %>
        </td>
        <td><%= user.average_score.floor(1).to_f %></td>
        <td><%= user.age %>代</td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/users/_average.html.erb
<h4>投稿履歴の<br>平均スコアランキング</h4>
<% avg = 0 %>
<% rank = 1 %>
<table class="table table-hover">
  <tr class="table-secondary">
    <th>順位</th>
    <th>ユーザー名</th>
    <th>平均スコア</th>
    <th>年齢</th>
  </tr>
  <% user_avg.each.with_index(1) do |user, i| %>
    <tr class="bg-light">
      <% if i == 1 %>
        <% avg = user.average_score %>
      <% end %>
      <% if user.average_score != avg %>
        <% rank = i %>
        <td>第<%= rank %>位</td>
        <td>
          <%= link_to user_path(user) do %>
            <%= user.name %>
          <% end %>
        </td>
        <td><%= user.average_score.floor(1).to_f %></td><!--to_fで小数点以下を表示させ、floor()で小数点以下の桁数を引数で指定-->
        <% avg = user.average_score %>
        <td><%= user.age %>代</td>
      <!--同順位の表示-->
      <% else %>
        <% avg = user.average_score %>
        <td>第<%= rank %>位</td>
        <td>
          <%= link_to user_path(user) do %>
            <%= user.name %>
          <% end %>
        </td>
        <td><%= user.average_score.floor(1).to_f %></td>
        <td><%= user.age %>代</td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/users/_show.html.erb
<h4 class="text-center pt-3">プロフィール</h4>
<div class="text-center"><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br /></div>
<ul type="none" class=" text-center p-0 mt-2">
  <li><%= user.name %></li>
  <li><%= user.gender %></li>
  <li><%= user.address %></li>
  <li>年齢：<%= user.age %>代</li>
  <li>
    平均スコア：
    <% if user.profile_score.present? %>
      <%= user.profile_score %>代
    <% else %>
      登録していません
    <% end %>
  </li>
  <li>紹介文</li>
</ul>
<div class="word-break">
  <!--入力通りの改行で表示-->
  <%= safe_join(user.introduction.split("\n"),tag(:br)) %>
</div>
<div class="text-center mt-2">
  フォロー
  <%= link_to following_user_path(@user) do %>
    <%= @user.following.count %>
  <% end %>
  フォロワー
  <%= link_to followers_user_path(@user) do %>
    <%= @user.followers.count %>
  <% end %><br>
<p>ユーザーレベル<%= @user.level %></p>
</div>
<div class="text-center">
  <% unless @user == current_user %>
    <% if current_user.following?(@user) %>
      <%= link_to 'フォローを外す', user_relationships_path(@user), method: :DELETE, class:"btn btn-outline-primary" %>
    <% else %>
      <%= link_to 'フォローする', user_relationships_path(@user), method: :POST, class:"btn btn-outline-primary" %>
    <% end %>
  <% end %><br>
  <div class="chat mt-2">
    <% if current_user != user %>
      <!--アンカーリンクで遷移後の表示位置の指定-->
      <%= link_to 'チャットを始める', chat_path(user.id, anchor: 'saikabu'), class:"btn btn-outline-secondary"%>
    <% end %>
  </div>
</div>

<div class="text-center">
  <% if user.id == current_user.id %>
    <p><%= link_to "プロフィール編集", edit_user_path(user), class: "fas fa-user-edit" %></p>
  <% end %><br />
</div>

app/views/users/edit.html.erb
<div class="container mt-4">
  <div class="row text-center">
    <div class="col-md-6 offset-3">
        <h4>プロフィール編集</h4>
        <% if @user.errors.any? %>
          <h3><%= @user.errors.count %>件のエラーが発生しました</h3>
          <% @user.errors.full_messages.each do |message| %>
            <div class="text-danger"><%= message %></div>
          <% end %>
        <% end %>
        <%= form_with model:@user, local:true do |f| %>

          <div class="field mt-3">
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
            <label for="inputImage" class="mb-4">プロフィール画像</label>
            <div class="ml-5"><%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %></div>
          </div>

          <div class="field my-1">
            <label for="inputName" class="m-0">ユーザー名</label><br>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
          </div>

          <div class="field-gender">
            <label for="inputGender" class="m-0">性別</label><br>
            <%= f.label :man, "男性"  %>
            <%= f.radio_button :gender, :男性 %>
            <%= f.label :woman, "女性"  %>
            <%= f.radio_button :gender, :女性 %>
          </div>

          <div class="field my-1">
            <label for="inputAge" class="m-0">年齢</label><br>
            <%= f.select :age, [["10代", "10"], ["20代", "20"], ["30代", "30"], ["40代", "40"], ["50代", "50"], ["60代", "60"], ["70代", "70"], ["80代", "80"]], include_blank: "選択して下さい" %><br />
          </div>

          <div class="field my-1">
            <label for="inputAddress" class="m-0">住所</label><br>
            <%= f.select :address, User.addresses.keys, {} %>
          </div>
          
          <div class="field my-1">
            <label for="inputProfile_score" class="m-0">平均スコア</label><br>
            <%= f.select :profile_score, [["130代", "130"],["120代", "120"], ["110代", "110"], ["100代", "100"], ["90代", "90"], ["80代", "80"], ["70代", "70"], ["60代", "60"]], include_blank: "選択して下さい" %><br />
          </div>

          <label for="inputIntroduction">紹介文</label><br />
          <%= f.text_area :introduction, id:"inputIntroduction", placeholder:"紹介文", size: "50x5" %><br />

          <%= f.submit "変更を保存" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col md-3 offset-3">
      <p class="text-center mt-3"><%= link_to "退会する",user_path(current_user.id), class: "destroy-user text-danger", method: :delete, "data-confirm" => "データが全て削除されます。本当に退会しますか？" %></p>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>フォロワー</h1>
      <table class="table">
        <% if @users.present? %>
        <tr class="table-secondary">
          <th>ユーザー名</th>
          <th>年齢</th>
          <th>住所</th>
          <th></th>
          <th></th>
        </tr>
          <% @users.each do |user| %>
            <tr class="bg-light">
              <td><%= user.name %></td>
              <td><%= user.age %>代</td>
              <td><%= user.address %></td>
              <td>
                <% if current_user != user %>
                  <%= link_to 'chatを始める', chat_path(user.id, anchor: 'saikabu'), class:"btn btn-outline-secondary" %>
                <% end %>
              </td>
              <td><%= link_to "詳細", user_path(user) %></td>
            <% end %>
          <% else %>
            ユーザーはいません
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/users/following.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>フォロー</h1>
      <table class="table">
        <% if @users.present? %>
        <tr class="table-secondary">
          <th>ユーザー名</th>
          <th>年齢</th>
          <th>住所</th>
          <th></th>
          <th></th>
        </tr>
          <% @users.each do |user| %>
            <tr class="bg-light">
              <td><%= user.name %></td>
              <td><%= user.age %>代</td>
              <td><%= user.address %></td>
              <td>
                <% if current_user != user %>
                  <%= link_to 'chatを始める', chat_path(user.id, anchor: 'saikabu'), class:"btn btn-outline-secondary"%>
                <% end %>
              </td>
              <td><%= link_to "詳細", user_path(user) %></td>
            <% end %>
          <% else %>
            ユーザーはいません
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-4 mt-5 p-0">
      <%= search_form_for @q do |f| %>
        <table>
          <h4>ユーザー検索</h4>
          <tr>
            <td width=120><%= f.label :name_or_introduction, "フリーワード" %></td>
            <td><%= f.search_field :name_or_introduction_cont, placeholder: "ゴルフ場名や県名など" %></td>
          </tr>
          <tr>
            <td><%= f.label :profile_score_eq, "平均スコア" %></td>
            <td><%= f.select :profile_score_eq, [["130代", "130"], ["120代", "120"], ["110代", "110"], ["100代", "100"], ["90代", "90"], ["80代", "80"], ["70代", "70"], ["60代", "60"]], {include_blank: "選択して下さい"}, class: 'user' %></td>
          </tr>
          <tr>
            <td><%= f.label :gender, "性別" %></td>
            <td>
            <%= f.radio_button :gender_eq, '', {:checked => true} %>指定なし
            <%= f.radio_button :gender_eq, 0 %>男性
            <%= f.radio_button :gender_eq, 1 %>女性
            </td>
          </tr>
          <tr>
            <td><%= f.label :address, "住所" %></td>
            <td><%= f.select :address_eq, [["北海道", 1], ["青森県", 2], ["岩手県", 3], ["宮城県", 4], ["秋田県", 5], ["山形県", 6], ["福島県", 7], ["茨城県", 8], ["栃木県", 9], ["群馬県", 10], ["埼玉県", 11], ["千葉県", 12],
                                      ["東京都", 13], ["神奈川県", 14], ["新潟県", 15], ["富山県", 16], ["石川県", 17], ["福井県", 18], ["山梨県", 19], ["長野県", 20], ["岐阜県", 21], ["静岡県", 22], ["愛知県", 23], ["三重県", 24],
                                      ["滋賀県", 25], ["京都府", 26], ["大阪府", 27], ["兵庫県", 28], ["奈良県", 29], ["和歌山県", 30], ["鳥取県", 31], ["島根県", 32], ["岡山県", 33], ["広島県", 34], ["山口県", 35], ["徳島県", 36],
                                      ["香川県", 37], ["愛媛県", 38], ["高知県", 39], ["福岡県", 40], ["佐賀県", 41], ["長崎県", 42], ["熊本県", 43], ["大分県", 44], ["宮崎県", 45], ["鹿児島県", 46], ["沖縄県", 47]], {include_blank: "選択して下さい"}, class: 'user' %></td>
          </tr>
          <tr>
            <td><%= f.submit "検索" %></td>
          </tr>
        </table>
      <% end %>
    </div>

    <div class="col-md-8">
      <h4>ユーザー一覧</h4>
      <table class="table">
        <tr class="table-secondary">
          <th><%= sort_link(@q, :name, "ユーザー名") %></th>
          <th><%= sort_link(@q, :profile_score, "平均スコア") %></th>
          <th><%= sort_link(@q, :age, "年齢") %></th>
          <th><%= sort_link(@q, :gender, "性別") %></th>
          <th><%= sort_link(@q, :address, "住所") %></th>
        </tr>
        <% @user_s.each do |user| %>
          <tr class="bg-light">
            <td>
              <%= link_to user_path(user) do %>
                <%= user.name %>
              <% end %>
            </td>
            <td><%= user.profile_score %>代</td>
            <td><%= user.age %>代</td>
            <td><%= user.gender %></td>
            <td><%= user.address %></td>
          <% end %>
        </tr>
      </table>
      <div class="pagination justify-content-center">
        <%= paginate @user_s %>
      </div>
    </div>
  </div>

</div>

app/views/users/rank.html.erb
<div class="container mt-4">
<% tab_age = 0 %>
<% user_age = 0 %>
  <div class="row justify-content-center">
    <div class="col-md-10">
      <ul class="nav nav-tabs" role="tablist">
        <li class="active" role="presentation">
          <a aria-controls="tab_a" data-toggle="tab" href="#tab_a" role="tab">全体</a>｜
        </li>
        <% 8.times do |i| %>
          <% tab_age += 10 %>
          <li role="presentation">
            <a aria-controls="tab<%= i %>" data-toggle="tab" href="#tab<%= i %>" role="tab"><%= tab_age %>代</a>｜
          </li>
        <% end %>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="tab_a" role="tabpanel">
          <%= render 'users/average', user_avg: @user_avg %>
        </div>
        <% title_age = 0%>
        <% 8.times do |i| %>
          <% title_age += 10 %>
          <div class="tab-pane" id="tab<%= i %>" role="tabpanel">
            <h4>投稿履歴の<br>平均スコアランキング(<%= title_age %>代)</h4>
            <% @user_avg_age = User.joins(:posts).group(:id).select("AVG(posts.score) as average_score, users.*").where(age: user_age += 10).order("average_score asc").limit(10) %>
            <%= render 'users/age', user_avg_age: @user_avg_age %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-md-3 px-2 bg-light">
      <%= render 'users/show', user: @user %>
      <!--スクロール化-->
      <% if @user.id == current_user.id %>
        <h5>フォロワーの投稿</h5>
        <% if @users.present? %>
          <div class="scroll">
            <table>
              <tr>
                <th>ユーザー</th>
                <th>タイトル</th>
              </tr>
              <% @follow_post.each do |post| %>
                <tr>
                  <th>
                    <%= link_to user_path(post.user) do %>
                      <%= post.user.name %>さん
                    <% end %>
                  </th>
                  <th>
                    <%= link_to post_path(post) do %>
                      <%= post.title %><br>
                    <% end %>
                  </th>
                </tr>
              <% end %>
            </table>
          </div>
        <% else %>
          <p>フォローしてみましょう</p>
        <% end %>
      <% end %>
    </div>

    <div class="col-md-9 pl-4 pr-0">
      <div class="row">
        <div class="col-md-3"><h4>スコア履歴</h4></div>
        <div class="col-md-3 offset-6"><h4><%= link_to '新規投稿', new_post_path, class:"btn btn-info" %></h4></div>
      </div>

      <div class="bg-light py-3">
      <% if @posts.chart_date.present? %>
        <%= line_chart @posts.chart_date, min: 60, xtitle: "日付", ytitle: "スコア", width: "100%", height: "200px", discrete: true, curve: false %>
      <% else%>
        <p class="text-center m-0">投稿がありません</p>
      <% end %>
      </div>
      <div class="my-post mt-3">
        <h4><%= @user.name %>さんの投稿一覧</h4>
        <% if @posts.present? %>
          <table class="table" style="table-layout:fixed;">
            <tr class="table-secondary">
              <th>タイトル</th>
              <th>プレー日</th>
              <th>スコア</th>
              <th>画像</th>
              <th style="width:200px;">内容</th>
            </tr>
            <% @posts.each do |post| %>
              <tr class="bg-light">
                <td class="text-overflow">
                  <%= link_to post_path(post) do %>
                    <%= post.title %></td>
                  <% end %>
                <td><%= post.date.strftime('%Y-%m-%d') %></td>
                <td><%= post.score %></td>
                <td>
                  <% if post.post_images.present? %>
                    <% post.post_images.each do |image| %>
                      <%= attachment_image_tag image, :image, :size =>"30x30" %>
                    <% end %>
                  <% else %>
                  <% end %>
                </td>
                <td class ="text-overflow"><%= post.impression %></td>
              </tr>
            <% end %>
          </table>
        <% else%>
          <p class="text-center m-0">投稿がありません</p>
        <% end %>
      </div>
    </div>
  </div>
</div>