config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get 'chat/:id' => 'chats#show', as: 'chat'
  get "/rank" => "users#rank"

  resources :users, only: [:index, :show, :edit, :update, :destroy]do
    resource :relationships, only: [:create, :destroy]
      member do
        get :following, :followers
      end
  end
  resources :posts, only: [:new, :create, :index, :show, :edit,:update, :destroy]do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :chats, only: [:create]
  resources :notifications, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  #optional: trueは、nilを許可するもの
  belongs_to :post, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true 
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :post_images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  validates :title, length: { in: 1..50 }
  validates :score, numericality: {only_integer: true}, allow_blank: true #整数のみスコアが未入力でも投稿可能
  validates :impression, presence: true, length: { maximum: 300 }
  
  accepts_attachments_for :post_images, attachment: :image

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.chart_date
    chart_date = []
    order(date: :asc).each do |post|
      chart_date << [ post.date.strftime('%Y-%m-%d'), post.score ]
    end
    return chart_date
  end
  
  # 投稿いいね通知
  def create_notification(current_user, user)
    past_notices = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ?", current_user.id, user.id, id, 'favorite'])
     
    if past_notices.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user.id,
        action: 'favorite'
      )
      notification.save
    end
  end
  # 投稿コメント通知
  def create_notification_comment(current_user, user)
    past_notices = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ?", current_user.id, user.id, id, 'comment'])
     
    if past_notices.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user.id,
        action: 'comment'
      )
      notification.save
    end
  end
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true, length: { maximum: 50 }
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :post
  attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :following_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :following_relationships, source: :followed
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :user_rooms
  has_many :chats

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :name, presence: true, length: { maximum: 10 }, uniqueness: true
  validates :age, presence: true
  validates :profile_score, presence: true
  validates :introduction, length: { maximum: 150 }

  attachment :profile_image
  enum gender: { 男性: 0, 女性: 1}
  enum address:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }

  def follow(user_id)
    following_relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following.include?(user)
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    redirect_to request.referer
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @user = User.find(current_user.id)
    @post = current_user.posts.new(post_params)
    @post.user_id = current_user.id
    # 投稿するごとにレベルが上がる
    @user.exp_sum += @post.exp.to_i
    if @user.level == 1
      @user.level += @user.exp_sum.to_i
    else
      @user.level = @user.exp_sum.to_i + 1
    end
    current_user.update(exp_sum: @user.exp_sum, level: @user.level)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def index
    @q = Post.ransack(params[:q])
    @post_s = @q.result(distinct: true).page(params[:page]).per(9)
  end

  def show
    @posts = Post.all
    @post = Post.find(params[:id])
    @user = @post.user
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user == current_user
      render "edit"
    else
      redirect_to post_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :date, :score, :impression, :exp, post_images_images: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GolGol</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <header class="shadow-sm">
    <nav class="navbar navbar-expand-md navbar-light bg-success">
      <div class="container my-3">
        <%= link_to image_tag('logo.png'), '/', class:"text-light" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item mr-3">
                <%= link_to 'マイページ', user_path(current_user.id), class:"text-light" %>
              </li>
              <% if unchecked_notifications.any? %>
                <i class="fa fa-circle" style="color: gold;"></i>
              <% end %>
              <li class="nav-item mr-3">
                <%= link_to '通知', notifications_path, class:"text-light" %>
              </li>
              <li class="nav-item mr-3">
                <%= link_to '会員一覧', users_path, class:"text-light" %>
              </li>
              <li class="nav-item mr-3">
                <%= link_to '投稿一覧', posts_path, class:"text-light" %>
              </li>
              <li class="nav-item mr-3">
                <%= link_to 'ランキング', rank_path, class:"text-light" %>
              </li>
              <li class="nav-item mr-3">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"text-light" %>
              </li>
            <% else %>
              <li class="nav-item mr-3">
                <%= link_to "新規登録", new_user_registration_path, class:"text-light" %>
              </li>
              <li class="nav-item mr-3">
                <%= link_to "ログイン", new_user_session_path, class:"text-light" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <body>
    <%= yield %>
  </body>
  <footer class="footer bg-success">
    <div class="container">
      <p class="text-center pt-3">GolGol</p>
    </div>
  </footer>
</html>